In [1]:
import tensorflow

In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3, 4]

In [6]:
print(np.array(my_list))

[1 2 3 4]


In [7]:
print(np.arange(1, 10))

[1 2 3 4 5 6 7 8 9]


In [8]:
# Casting nested list into 3 by 3 matrix
nested_list = [[1,2,3], [4,5,6], [7,8,9]]
print(np.array(nested_list))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# Step size of arange
np.arange(20, 100, 6)

array([20, 26, 32, 38, 44, 50, 56, 62, 68, 74, 80, 86, 92, 98])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
# Shape (4, 4, 4)
np.zeros((4, 4, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
# np.ones
np.ones((1, 1))

array([[1.]])

In [20]:
# linspace -> start, end and number of points
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [25]:
# diagonals of ones
np.eye(5)
# random distribution from 0 to 1
np.random.rand(2)

array([0.61449474, 0.47486339])

In [26]:
# normal distribution
np.random.randn(2)



array([ 0.53291534, -0.83469244])

In [41]:
np.random.seed(2) # Leaving this here implies that the random numbers after the next execution will be the same
print(np.random.randint(1, 10, 10))

[9 9 7 3 9 8 3 2 6 5]


In [44]:
print(np.random.randint(1, 10, 10))

[5 2 8 9 3 9 8 2 7 9]


In [50]:
# reshaping array 
arr = np.random.randint(1, 200, (2, 3))
print(arr)


np.reshape(arr, (3, 2)) # The new shape must be contain the same number of elements

[[ 98 147  88]
 [151  44  53]]


array([[ 98, 147],
       [ 88, 151],
       [ 44,  53]])

In [61]:
# max and maxvalue index location
#arr.max(), arr.argmax()
print(arr) 
print(arr[0, 1]) # Indexing
print(arr[0:2]) # Slicing


[0.70204204 0.70654201 0.48102176 0.96031373 0.42602253 0.32287421
 0.76193    0.93262856 0.71121724 0.51743076]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [68]:

# Unlike normal Python list, arrays can be broadcasted, a single value can replace slice of the array

arr = np.random.randint(0, 100, 10)
print(arr)

arr[2:6] = 10000 # Multiple values get 10000
print(arr)

[36 22 19 95 17 45 72 37  9 21]
[   36    22 10000 10000 10000 10000    72    37     9    21]


In [78]:
# Assigning array to new variable, always points to the old array. So use copy
new_arr = arr[2:8]
new_arr[0] = 234253523
#print(new_arr)
print(arr) 


# Quite useful
arr1 = np.linspace(0, 10, 11)
print(arr1)
print(arr1[arr1 < 6]) # Use as a filter

[       36        22 234253523         0         0     10000        72
        37         9        21]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0. 1. 2. 3. 4. 5.]


Operations


In [92]:
arr = np.arange(10, 20)
arr = arr.reshape(2, 5)
arr + 5
arr - arr
arr / 2

print(arr.sum()) # taking sum of an array
print(arr.mean()) # taking mean of an array
print(np.sqrt(arr)) # taking sqrt
print(np.negative(arr)) # taking negative

145
14.5
[[3.16227766 3.31662479 3.46410162 3.60555128 3.74165739]
 [3.87298335 4.         4.12310563 4.24264069 4.35889894]]
[[-10 -11 -12 -13 -14]
 [-15 -16 -17 -18 -19]]
